<?php 
set_time_limit(2000);
ini_set('memory_limit', '110000M');
session_start();
$uploadedfile11 = $_POST['filee'];
include('../../../../wp-config.php');
global $wpdb;
if($uploadedfile11 != "")
{
$file_name = $uploadedfile['name'];

$file_extent = explode(".",$uploadedfile11);
$endd = end($file_extent); 
if($endd=="xls" || $endd=="xlsx")
{
	$uploadedfile = $_FILES['filee'];
	if ( ! function_exists( 'wp_handle_upload' ) ) {
		require_once( ABSPATH . 'wp-admin/includes/file.php' );
	}
	$upload_overrides = array( 'test_form' => false );
	$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
	echo $img_url = $movefile[url];
	if ( $movefile && !isset( $movefile['error'] ) ) {
		"File is valid, and was successfully uploaded.\n";
		$file_check=var_dump( $movefile);
		$img_url = $movefile[url];
		$post_id = $wpdb->insert( 'im_upload_file', array(
		'url' => $img_url)
		);
		print_r($post_id);
		$_SESSION['post_id_file'] = $post_id;
	} 
	else 
	{
		/**
		* Error generated by _wp_handle_upload()
		* @see _wp_handle_upload() in wp-admin/includes/file.php
		*/
		$movefile['error'];
	}
	echo $post_id;;
}
else
{
	echo "2A";
}
}
else
{
	echo "3A";
}
